version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:8597

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8597:8597"
    env_file:
      - ./server/.env
    depends_on:
      - python_backend

  python_backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./python_backend/.env
